### ISSUE TITLE
How do you implement Shared elements between Activities when using an ListView with images.

### ISSUE THREAD

**Issue by IamJackppot** [lgvalle/Material-Animations#10]
I have a ListView with a custom adapter that loads images and text. How would I be able to utilize the "Shared elements between Activities" when clicking on each of the items? I'm confused because if you click on an item, then set the transition effect to animate the ImageView, won't all of the images be animated rather than the one that corresponds with the item row you have clicked?

If you could give an example, that would be extremely helpful. Thank you.

**Comment by lgvalle** [comment]
Sorry I'm quite busy now, but a real example with list (although implemented using RecyclerView) is the next thing I want to add here. Not sure when I will have the time though.

**Comment by GautamGupta** [comment]
Check https://github.com/alexjlockwood/activity-transitions

However it uses a recyclerview

**Comment by lgvalle** [comment]
@IamJackppot Sorry for the delay.
I have recently updated the code of this project with much more examples. Check out shared element transition from recyclerview here:

https://github.com/lgvalle/Material-Animations/blob/master/app%2Fsrc%2Fmain%2Fjava%2Fcom%2Flgvalle%2Fmaterial_animations%2FSamplesRecyclerAdapter.java#L41
