### ISSUE TITLE
Reverse animation not working when using supportActionBar's back (home) button

### ISSUE THREAD

**Issue by nidheeshdas** [lgvalle/Material-Animations#11]
I'm using shared element transition and its working well, but only in forward direction. When I press back arrow in the action bar (not the back button), there is no reverse transition of the shared transition. 

Although this works when you press the back button. 

Any help ?

**Comment by lgvalle** [comment]
Hi, can you provide the code involved of your activity? Are you overriding the back behaviour of this button?

**Comment by nidheeshdas** [comment]
I've fixed it. I was not calling `supportFinishAfterTransition()` in the back button handler. 

I should've closed this issue before.
