### ISSUE TITLE
Invalid slide direction

### ISSUE THREAD

**Issue by liunewshine** [lgvalle/Material-Animations#17]
when I run the app, stopped and logcat errors:
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.lgvalle.material_animations/com.lgvalle.material_animations.MainActivity}: java.lang.IllegalArgumentException: Invalid slide direction

**Comment by lgvalle** [comment]
`Invalid slide direction` error is most likely caused because I'm using `START` as a direction and the API level of your device can't handle that.
Try changing it to `LEFT` for example

**Comment by ShkurtiA** [comment]
I had the same problem, LEFT is the solution

**Comment by lgvalle** [comment]
Fixed here https://github.com/lgvalle/Material-Animations/pull/22
