### ISSUE TITLE
java.lang.NoClassDefFoundError: android.transition.Explode exception when importing the project in eclipse

### ISSUE THREAD

**Issue by manpreetsinghsodhi** [lgvalle/Material-Animations#2]
Hi i am getting following exception in logcat when i import and run this project 

05-23 09:45:56.073: E/AndroidRuntime(480): FATAL EXCEPTION: main
05-23 09:45:56.073: E/AndroidRuntime(480): java.lang.NoClassDefFoundError: android.transition.Explode
05-23 09:45:56.073: E/AndroidRuntime(480): 	at com.lgvalle.material_animations.MainActivity.setupWindowAnimations(MainActivity.java:36)
05-23 09:45:56.073: E/AndroidRuntime(480): 	at com.lgvalle.material_animations.MainActivity.onCreate(MainActivity.java:31)
05-23 09:45:56.073: E/AndroidRuntime(480): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1048)
05-23 09:45:56.073: E/AndroidRuntime(480): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1712)
05-23 09:45:56.073: E/AndroidRuntime(480): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1764)
05-23 09:45:56.073: E/AndroidRuntime(480): 	at android.app.ActivityThread.access$1500(ActivityThread.java:122)
05-23 09:45:56.073: E/AndroidRuntime(480): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1002)
05-23 09:45:56.073: E/AndroidRuntime(480): 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-23 09:45:56.073: E/AndroidRuntime(480): 	at android.os.Looper.loop(Looper.java:132)
05-23 09:45:56.073: E/AndroidRuntime(480): 	at android.app.ActivityThread.main(ActivityThread.java:4025)
05-23 09:45:56.073: E/AndroidRuntime(480): 	at java.lang.reflect.Method.invokeNative(Native Method)
05-23 09:45:56.073: E/AndroidRuntime(480): 	at java.lang.reflect.Method.invoke(Method.java:491)
05-23 09:45:56.073: E/AndroidRuntime(480): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:841)
05-23 09:45:56.073: E/AndroidRuntime(480): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:599)
05-23 09:45:56.073: E/AndroidRuntime(480): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by lgvalle** [comment]
Hi, sorry I didn't see this.

` java.lang.NoClassDefFoundError: android.transition.Explode`

Seems that you are not compiling against Lollipop (API 21)
