### ISSUE TITLE
Add support for Maven or Release GitHub Release

### ISSUE THREAD

**Issue by bliveinhack** [lgvalle/Material-Animations#29]
Great Library! it would be great if someone can publish it on Maven or @lgvalle Please make Github Release to be use with jitpack.

Thanks.

**Comment by lgvalle** [comment]
Hi, thanks. Glad you like the repo, but it is just a group of examples. Is not a library and is not meant to be used as one.

**Comment by bliveinhack** [comment]
Ahhh...i see. Anyway nice examples. do you have any reference for backporting to oloder API?

Thanks.

**Comment by lgvalle** [comment]
Sorry but there is no easy way to backport this animations to older API versions. It is also discouraged by Google.
