### ISSUE TITLE
Not working with support library

### ISSUE THREAD

**Issue by gagan20** [lgvalle/Material-Animations#31]
I am trying to use shared element animation in my project and I am using support library for fragments.
I tried the same procedure to add shared element animation but it is not working.
I tested the code on Android 6.0

**Comment by lgvalle** [comment]
Since your issue is not specifically related to this project I think the right place to ask the question would be a site like http://stackoverflow.com/

It would be better to open the conversation there. If you mention me there I'll do my best to help with your issue.
