### ISSUE TITLE
why my Transitions between Activities not work?

### ISSUE THREAD

**Issue by chenchongyu** [lgvalle/Material-Animations#36]
I do it it like this in my BasicActivity onCreate():

_getWindow().requestFeature(Window.FEATURE_CONTENT_TRANSITIONS);
setupWindowAnimations();
super.setContentView(R.layout.layout_base);
setContentView(getContentViewID());_

My setupWindowAnimations() function like this:
_protected void setupWindowAnimations() {
			L.i("setupWindowAnimations");
			Slide slide = (Slide) TransitionInflater.from(this).inflateTransition(R.transition.activity_slide_out);
			Fade fade = (Fade) TransitionInflater.from(this).inflateTransition(R.transition.activity_fade_in);
			getWindow().setEnterTransition(slide);
			getWindow().setExitTransition(fade);
	}_

when I call startActivity(A,B), the animations not worked.Can u help me? Thanks a lot!

**Comment by guliash** [comment]
@chenchongyu try this to start your activity:
```java
Intent intent = new Intent(this, YourActivity.class);
ActivityOptionsCompat options = ActivityOptionsCompat.makeSceneTransitionAnimation(this);
startActivity(intent, options.toBundle());
```

**Comment by chenchongyu** [comment]
Thanks for reply! I have another question.May I use this animation below sdk 21 ?

**Comment by guliash** [comment]
@chenchongyu I don't know. But maybe this would be useful [stackoverflow](http://stackoverflow.com/questions/27344357/android-5-activity-transition-on-lower-api)

**Comment by lgvalle** [comment]
It is usually not recommended to try to fake those transitions on lower API levels. But it's up to you :)

**Comment by chainstair** [comment]
@guliash Thanks bro... This worked for me

**Comment by fllaryora** [comment]
@guliash Thank you! This worked for me.
 
> override fun onClick(view: View?) {
>         if (view != null) {
>             val intent: Intent = Intent(view.context, DisksActivity::class.java)
>             val bundle: Bundle = Bundle()
>             bundle.putString(view.context.getString(R.string.EXTRA_DISK_TITLE), itemView.tag.toString())
>             intent.putExtras(bundle)
>             //TODO try shared element feature (i have to translate my comments)
>             val options = ActivityOptionsCompat.makeSceneTransitionAnimation( view.context as Activity)
>             view.context.startActivity(intent,options.toBundle())
>         }
> 
>     }

I had the same issue that @chenchongyu had had with transitions, but in 2018 and in kotlin.

@lgvalle right: fake animations for lowers API levels are ugly.
