### ISSUE TITLE
about @BindingAdapter

### ISSUE THREAD

**Issue by Sausure** [lgvalle/Material-Animations#39]
I have an issue about "@BindingAdapter".
In project,has a line as "@BindingAdapter("bind:colorTint")",and every time I build the project AS would throw a wrong like "Error:(23, 24) 警告: Application namespace for attribute bind:colorTint will be ignored".
Although the project can run,but I am not happy with it.
So I change that line code to "@BindingAdapter("android:colorTint")",then change "app:colorTint" to "android:colorTint".or just change "@BindingAdapter("bind:colorTint")" to "@BindingAdapter("colorTint")",now AS never throw that wrong again.
Could you tell me why?

**Comment by lgvalle** [comment]
Take a look here: http://developer.android.com/intl/pt-br/reference/android/databinding/BindingAdapter.html
It will explain all about Data Binding better than I ;)

**Comment by Sausure** [comment]
thanks!!

**Comment by amyliu1062** [comment]
@lgvalle   i use "@BindingAdapter("android:colorTint")"  and "android:colorTint" 
![image](https://cloud.githubusercontent.com/assets/6679526/23787801/b2b260fc-05ae-11e7-81c3-f72bf44858d4.png)
the result is the ImageView can`t  change color.
