### ISSUE TITLE
Incompatible types

### ISSUE THREAD

**Issue by multivoltage** [lgvalle/Material-Animations#42]
If I write this code like tutorial:
`      Fade fade = TransitionInflater.from(this).inflateTransition(R.transition.activity_fade);
        getWindow().setEnterTransition(fade);`

Androd give me Incompatible types. So I tried:
      Transition fade = TransitionInflater.from(this).inflateTransition(R.transition.activity_fade);
        getWindow().setEnterTransition(fade);

and same for Activity B. This dont generate error, but it doesn't work

**Comment by lgvalle** [comment]
Try casting to `Fade` in the first example
