### ISSUE TITLE
Databinding

### ISSUE THREAD

**Issue by mahaicious** [lgvalle/Material-Animations#44]
where is the databinding folder in this project?

**Comment by RassProjects** [comment]
if you are finding **"ActivityAnimations1Binding"**  from below code (Code from AnimationsActivity1 from sample )

    ActivityAnimations1Binding binding = DataBindingUtil.setContentView(this, R.layout.activity_animations1);
        sample = (Sample) getIntent().getExtras().getSerializable(EXTRA_SAMPLE);
        binding.setAnimationsSample(sample);

then this is generated by Data-binding rules of android read here [https://developer.android.com/topic/libraries/data-binding/index.html ](url)

for quick 
1) it is Depends on layout xml -----R.layout.**activity_animations1** and uses 
2) Binding  suffix 

so data-binding class will be ActivityAnimations1Binding.

Thanks

**Comment by lgvalle** [comment]
Thanks for clarifying @RassProjects 👍

**Comment by RassProjects** [comment]
Pleasure is all mine.
