### ISSUE TITLE
Is that have some demos for android 4.x ?

### ISSUE THREAD

**Issue by houwei14350** [lgvalle/Material-Animations#46]
Is that have some demos for android 4.x ? I wanna add this to my App but it`s not for android API which is before android Lollipe

**Comment by splm** [comment]
it could run on 4.x.My device version is 4.4.

**Comment by xhAndroid** [comment]
My device version is 4.4.4, not work. For help

**Comment by wei3** [comment]
device version is 4.4.4, not work, me too

**Comment by lgvalle** [comment]
Some of this repo examples are not meant to run on version less than Lollipop.
There is a new `android.support.transition` package. I suggest you look in there for more info on how to implement transitions in old devices https://developer.android.com/reference/android/support/transition/package-summary.html
