### ISSUE TITLE
custom transitioning view

### ISSUE THREAD

**Issue by JimmyKent** [lgvalle/Material-Animations#48]
I have a view that has a button,and 4 imageview. I want the 4 imageviews do Explode transition but I dont want the button do Explode. how to do ?
I have a doubt that the below code need to set before setContentView.
getWindow().setExitTransition(mExplode);
but after setContentView, I get the view id.
then use this code to setTransition.
mExplode.addTarget(mImgRl);
hope your reply !
sincerely

**Comment by lgvalle** [comment]
You can do something like:

`transition.excludeTarget(findViewById(button), true);`

**Comment by JimmyKent** [comment]
it works！thanks
