### ISSUE TITLE
How to show animations in transitions between fragments

### ISSUE THREAD

**Issue by hzw1199** [lgvalle/Material-Animations#6]
I want to show Animate shared elements in transitions between fragments, but find no samples. How to make it? Thank u

**Comment by lgvalle** [comment]
Can you provide an example of what you want to do?

**Comment by Labman003** [comment]
How to shared elements between Fragments?

**Comment by lgvalle** [comment]
@hzw1199 @Labman003 Check out the updated sample here: https://github.com/lgvalle/Material-Animations/blob/master/app%2Fsrc%2Fmain%2Fjava%2Fcom%2Flgvalle%2Fmaterial_animations%2FSharedElementActivity.java
